version: "4.6"
services:
  nanokraan:
    build: .
    image: nl_nano/nanokraan
    container_name: nanokraan
    restart: unless-stopped
    ports:
      - "0.0.0.0:3000:3000"
      - "0.0.0.0:3001:3001"
    volumes:
      - ./:/usr/src/app/